#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# backup.sh  —  Audit Tool Automated Backup
#
# วิธีใช้:
#   bash backup.sh              # backup ทุกอย่าง (database + attachments)
#   bash backup.sh --db-only    # backup database เท่านั้น
#   bash backup.sh --files-only # backup ไฟล์แนบเท่านั้น
#   bash backup.sh --install-cron # ติดตั้ง cron jobs แล้วออก
#   bash backup.sh --list       # แสดงรายการ backup ที่มีอยู่
#   bash backup.sh --prune      # ลบ backup เก่ากว่า BACKUP_RETENTION_DAYS วัน
#
# Cron ที่ติดตั้งโดย --install-cron:
#   Database  : ทุกคืน 02:00
#   Attachments: ทุกอาทิตย์ 03:00 (วันอาทิตย์)
#   Prune     : ทุกคืน 04:00
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✓${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; }

# ── Parse flags ───────────────────────────────────────────────────────────────
DO_DB=true
DO_FILES=true
INSTALL_CRON=false
LIST_ONLY=false
PRUNE_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --db-only)       DO_DB=true;  DO_FILES=false ;;
    --files-only)    DO_DB=false; DO_FILES=true  ;;
    --install-cron)  INSTALL_CRON=true           ;;
    --list)          LIST_ONLY=true              ;;
    --prune)         PRUNE_ONLY=true             ;;
  esac
done

# ── Load .env ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE=""
COMPOSE_DIR=""

if   [[ -f "/opt/audit-tool/.env" ]];   then ENV_FILE="/opt/audit-tool/.env";   COMPOSE_DIR="/opt/audit-tool"
elif [[ -f "${SCRIPT_DIR}/.env" ]];     then ENV_FILE="${SCRIPT_DIR}/.env";     COMPOSE_DIR="${SCRIPT_DIR}"
elif [[ -f "${SCRIPT_DIR}/../.env" ]];  then ENV_FILE="${SCRIPT_DIR}/../.env";  COMPOSE_DIR="${SCRIPT_DIR}"
fi

if [[ -z "$ENV_FILE" ]]; then
  error "ไม่พบไฟล์ .env — กรุณารัน install.sh ก่อน"
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

DOMAIN="${DOMAIN:-localhost}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD not set}"

# ── Backup settings ───────────────────────────────────────────────────────────
BACKUP_DIR="${BACKUP_DIR:-/var/backups/audit-tool}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-30}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DATE_TAG=$(date +%Y%m%d)

COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yml"

# ── Verify compose file ───────────────────────────────────────────────────────
if [[ ! -f "$COMPOSE_FILE" ]]; then
  error "ไม่พบ docker-compose.yml ที่ ${COMPOSE_FILE}"
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# --install-cron : ติดตั้ง cron jobs แล้วออก
# ─────────────────────────────────────────────────────────────────────────────
if $INSTALL_CRON; then
  BACKUP_SCRIPT_PATH="$(realpath "$0")"
  BACKUP_LOG="/var/log/audit-tool-backup.log"

  cat > /etc/cron.d/audit-tool-backup <<CRON
# Audit Tool — Automated Backup Cron Jobs
# Generated by backup.sh on $(date)

# Database backup — ทุกคืน 02:00
0 2 * * * root bash ${BACKUP_SCRIPT_PATH} --db-only >> ${BACKUP_LOG} 2>&1

# Attachment backup — ทุกอาทิตย์ 03:00 (วันอาทิตย์)
0 3 * * 0 root bash ${BACKUP_SCRIPT_PATH} --files-only >> ${BACKUP_LOG} 2>&1

# Prune old backups — ทุกคืน 04:00
0 4 * * * root bash ${BACKUP_SCRIPT_PATH} --prune >> ${BACKUP_LOG} 2>&1
CRON

  chmod 644 /etc/cron.d/audit-tool-backup
  touch "$BACKUP_LOG"

  success "Cron jobs installed:"
  echo ""
  echo -e "  ${BOLD}Database backup${NC}    : ทุกคืนเวลา 02:00"
  echo -e "  ${BOLD}Attachment backup${NC}  : ทุกอาทิตย์เวลา 03:00"
  echo -e "  ${BOLD}Prune old backups${NC}  : ทุกคืนเวลา 04:00 (เก็บไว้ ${BACKUP_RETENTION_DAYS} วัน)"
  echo -e "  ${BOLD}Log file${NC}           : ${BACKUP_LOG}"
  echo -e "  ${BOLD}Cron file${NC}          : /etc/cron.d/audit-tool-backup"
  echo ""
  exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# --list : แสดงรายการ backup
# ─────────────────────────────────────────────────────────────────────────────
if $LIST_ONLY; then
  echo ""
  echo -e "${BOLD}── Backup files in ${BACKUP_DIR} ──${NC}"
  echo ""

  if [[ ! -d "$BACKUP_DIR" ]]; then
    warn "ไม่พบ backup directory: ${BACKUP_DIR}"
    exit 0
  fi

  # Database backups
  echo -e "${BLUE}Database backups:${NC}"
  db_count=0
  db_size=0
  while IFS= read -r -d '' f; do
    sz=$(stat -c%s "$f" 2>/dev/null || echo 0)
    db_size=$((db_size + sz))
    ((db_count++)) || true
    printf "  %-50s  %s\n" "$(basename "$f")" "$(du -h "$f" | cut -f1)"
  done < <(find "${BACKUP_DIR}/db" -name "*.sql.gz" -print0 2>/dev/null | sort -z)
  [[ $db_count -eq 0 ]] && echo "  (ไม่มี backup)"
  echo "  รวม: ${db_count} ไฟล์"
  echo ""

  # Attachment backups
  echo -e "${BLUE}Attachment backups:${NC}"
  att_count=0
  while IFS= read -r -d '' f; do
    ((att_count++)) || true
    printf "  %-50s  %s\n" "$(basename "$f")" "$(du -h "$f" | cut -f1)"
  done < <(find "${BACKUP_DIR}/attachments" -name "*.tar.gz" -print0 2>/dev/null | sort -z)
  [[ $att_count -eq 0 ]] && echo "  (ไม่มี backup)"
  echo "  รวม: ${att_count} ไฟล์"
  echo ""

  total_size=$(du -sh "$BACKUP_DIR" 2>/dev/null | cut -f1 || echo "0")
  echo -e "  ${BOLD}ขนาดรวมทั้งหมด: ${total_size}${NC}"
  echo ""
  exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# --prune : ลบ backup เก่า
# ─────────────────────────────────────────────────────────────────────────────
prune_backups() {
  if [[ ! -d "$BACKUP_DIR" ]]; then return; fi

  info "Pruning backups older than ${BACKUP_RETENTION_DAYS} days..."
  local removed=0

  while IFS= read -r -d '' f; do
    rm -f "$f"
    ((removed++)) || true
    info "  Removed: $(basename "$f")"
  done < <(find "$BACKUP_DIR" \
    \( -name "*.sql.gz" -o -name "*.tar.gz" -o -name "*.log" \) \
    -mtime "+${BACKUP_RETENTION_DAYS}" \
    -print0 2>/dev/null)

  # Remove empty date directories
  find "$BACKUP_DIR" -type d -empty -delete 2>/dev/null || true

  if [[ $removed -eq 0 ]]; then
    info "ไม่มี backup เก่าที่ต้องลบ"
  else
    success "ลบ ${removed} ไฟล์เก่าแล้ว"
  fi
}

if $PRUNE_ONLY; then
  prune_backups
  exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# Main backup
# ─────────────────────────────────────────────────────────────────────────────
mkdir -p "${BACKUP_DIR}/db"
mkdir -p "${BACKUP_DIR}/attachments"
mkdir -p "${BACKUP_DIR}/logs"

LOG_FILE="${BACKUP_DIR}/logs/backup_${TIMESTAMP}.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Audit Tool Backup — $(date '+%Y-%m-%d %H:%M:%S')"
echo "  Retention: ${BACKUP_RETENTION_DAYS} days"
echo "════════════════════════════════════════════════════════"
echo ""

BACKUP_OK=true

# ─────────────────────────────────────────────────────────────────────────────
# Database backup
# ─────────────────────────────────────────────────────────────────────────────
backup_database() {
  echo -e "${BOLD}── Database Backup ──────────────────────────────────────${NC}"

  # Verify postgres is running
  if ! docker compose -f "$COMPOSE_FILE" exec -T postgres \
      pg_isready -U postgres &>/dev/null 2>&1; then
    error "PostgreSQL ไม่ได้รันอยู่ — ข้ามการ backup database"
    BACKUP_OK=false
    return
  fi

  local db_backup_dir="${BACKUP_DIR}/db/${DATE_TAG}"
  mkdir -p "$db_backup_dir"
  local out_file="${db_backup_dir}/database_${TIMESTAMP}.sql.gz"
  local latest_link="${BACKUP_DIR}/db/latest.sql.gz"

  info "Dumping PostgreSQL (public schema)..."

  # pg_dump inside container → gzip → save to host via exec
  if docker compose -f "$COMPOSE_FILE" exec -T postgres \
      sh -c "PGPASSWORD='${POSTGRES_PASSWORD}' pg_dump \
        -U postgres -d postgres \
        --schema=public \
        --no-owner --no-acl \
        --format=plain" \
      | gzip -9 > "$out_file"; then

    local size
    size=$(du -h "$out_file" | cut -f1)
    success "Database backup saved: $(basename "$out_file") (${size})"

    # Update latest symlink
    ln -sf "$out_file" "$latest_link"
    info "Symlink updated: ${latest_link}"

    # Verify the dump (check it's not empty)
    local line_count
    line_count=$(zcat "$out_file" | wc -l)
    if [[ "${line_count:-0}" -lt 10 ]]; then
      warn "Dump อาจว่างเปล่า (${line_count} lines) — ตรวจสอบด้วย: zcat ${out_file} | head"
    else
      info "Dump verified: ${line_count} lines"
    fi
  else
    error "pg_dump ล้มเหลว"
    rm -f "$out_file"
    BACKUP_OK=false
  fi

  echo ""
}

# ─────────────────────────────────────────────────────────────────────────────
# Attachment backup (MinIO → tar.gz)
# ─────────────────────────────────────────────────────────────────────────────
backup_attachments() {
  echo -e "${BOLD}── Attachment Backup ────────────────────────────────────${NC}"

  # Verify minio is running (use the HTTP health endpoint to avoid needing mc alias)
  if ! docker compose -f "$COMPOSE_FILE" exec -T minio \
      curl -sf http://localhost:9000/minio/health/live &>/dev/null 2>&1; then
    error "MinIO ไม่ได้รันอยู่ — ข้ามการ backup attachments"
    BACKUP_OK=false
    return
  fi

  local att_backup_dir="${BACKUP_DIR}/attachments/${DATE_TAG}"
  mkdir -p "$att_backup_dir"
  local tmp_dir
  tmp_dir=$(mktemp -d)
  local out_file="${att_backup_dir}/attachments_${TIMESTAMP}.tar.gz"
  local latest_link="${BACKUP_DIR}/attachments/latest.tar.gz"

  info "Downloading files from MinIO bucket: ncr-attachments..."

  # Mirror MinIO bucket → temp directory inside container, then docker cp out
  if docker compose -f "$COMPOSE_FILE" exec -T minio \
      sh -c "mc alias set local http://localhost:9000 '${MINIO_ROOT_USER}' '${MINIO_ROOT_PASSWORD}' >/dev/null 2>&1 || true; \
             mkdir -p /tmp/backup_attachments; \
             mc mirror --overwrite local/storage/ncr-attachments /tmp/backup_attachments/ 2>&1"; then

    # Copy from container to host tmp dir
    docker cp \
      "$(docker compose -f "$COMPOSE_FILE" ps -q minio)":/tmp/backup_attachments/. \
      "${tmp_dir}/"

    # Cleanup inside container
    docker compose -f "$COMPOSE_FILE" exec -T minio \
      rm -rf /tmp/backup_attachments 2>/dev/null || true

    # Count files
    local file_count
    file_count=$(find "$tmp_dir" -type f | wc -l)
    info "Downloaded ${file_count} file(s) from MinIO"

    if [[ "$file_count" -gt 0 ]]; then
      # Create tar.gz
      tar -czf "$out_file" -C "$tmp_dir" .
      local size
      size=$(du -h "$out_file" | cut -f1)
      success "Attachment backup saved: $(basename "$out_file") (${size}, ${file_count} files)"

      # Update latest symlink
      ln -sf "$out_file" "$latest_link"
      info "Symlink updated: ${latest_link}"
    else
      info "Bucket ว่างเปล่า — ไม่มีไฟล์ที่ต้อง backup"
      rm -rf "$tmp_dir"
      return
    fi
  else
    error "ไม่สามารถ mirror MinIO bucket ได้"
    BACKUP_OK=false
  fi

  rm -rf "$tmp_dir"
  echo ""
}

# ─────────────────────────────────────────────────────────────────────────────
# Run selected backups
# ─────────────────────────────────────────────────────────────────────────────
$DO_DB    && backup_database
$DO_FILES && backup_attachments

# ─────────────────────────────────────────────────────────────────────────────
# Prune old backups (always runs after successful backup)
# ─────────────────────────────────────────────────────────────────────────────
echo -e "${BOLD}── Pruning Old Backups ──────────────────────────────────${NC}"
prune_backups
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
total_size=$(du -sh "$BACKUP_DIR" 2>/dev/null | cut -f1 || echo "?")

echo "════════════════════════════════════════════════════════"
if $BACKUP_OK; then
  echo -e "  ${GREEN}${BOLD}✅  Backup เสร็จสมบูรณ์${NC}"
else
  echo -e "  ${YELLOW}${BOLD}⚠   Backup เสร็จ (มีบางอย่างผิดพลาด — ดู log)${NC}"
fi
echo "  Backup dir : ${BACKUP_DIR}"
echo "  Total size : ${total_size}"
echo "  Log file   : ${LOG_FILE}"
echo "  Retention  : ${BACKUP_RETENTION_DAYS} days"
echo "════════════════════════════════════════════════════════"
echo ""

# Remove today's log if it's too small (error before any output)
log_size=$(stat -c%s "$LOG_FILE" 2>/dev/null || echo 0)
[[ "${log_size:-0}" -lt 50 ]] && rm -f "$LOG_FILE" || true

$BACKUP_OK && exit 0 || exit 1
